baseURL: https://cultureofcode.net
languageCode: en
title: "Culture of Code"
theme: coc
paginate: 9
ignoreErrors:
  - "error-remote-getjson"

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokailight
    tabWidth: 2
  goldmark:
    parser:
      attribute:
        block: true
        title: true
      wrapStandAloneImageWithinParagraph: false
    renderer:
      unsafe: true


params:
  authorDisplayName: kenneth
  authorUrl: https://kennethbowen.com
  authorEmail: kenneth@kennethbowen.com
