# TODO fill in and GPLv3
name = "Coc"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Cultor of Code Hugo Theme"
homepage = "https://cultureofcode.online"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Kenneth Bowen"
  homepage = "https://kennethbowen.com"
